@echo off
cd
title Now Downloading the images of Apple site...
cls

wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_large.jpg -O overview/images/faces_photo_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_large_2x.jpg -O overview/images/faces_photo_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_medium.jpg -O overview/images/faces_photo_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_medium_2x.jpg -O overview/images/faces_photo_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_small.jpg -O overview/images/faces_photo_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photo_small_2x.jpg -O overview/images/faces_photo_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large.jpg -O overview/images/faces_photoalbum_coolgirl_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large_2x.jpg -O overview/images/faces_photoalbum_coolgirl_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium.jpg -O overview/images/faces_photoalbum_coolgirl_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium_2x.jpg -O overview/images/faces_photoalbum_coolgirl_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small.jpg -O overview/images/faces_photoalbum_coolgirl_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small_2x.jpg -O overview/images/faces_photoalbum_coolgirl_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_large.jpg -O overview/images/faces_photoalbum_coolguy_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_large_2x.jpg -O overview/images/faces_photoalbum_coolguy_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_medium.jpg -O overview/images/faces_photoalbum_coolguy_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_medium_2x.jpg -O overview/images/faces_photoalbum_coolguy_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_small.jpg -O overview/images/faces_photoalbum_coolguy_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolguy_small_2x.jpg -O overview/images/faces_photoalbum_coolguy_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_large.jpg -O overview/images/faces_photoalbum_longboard_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_large_2x.jpg -O overview/images/faces_photoalbum_longboard_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_medium.jpg -O overview/images/faces_photoalbum_longboard_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_medium_2x.jpg -O overview/images/faces_photoalbum_longboard_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_small.jpg -O overview/images/faces_photoalbum_longboard_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_longboard_small_2x.jpg -O overview/images/faces_photoalbum_longboard_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_large.jpg -O overview/images/faces_photoalbum_skateboard_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_large_2x.jpg -O overview/images/faces_photoalbum_skateboard_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_medium.jpg -O overview/images/faces_photoalbum_skateboard_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_medium_2x.jpg -O overview/images/faces_photoalbum_skateboard_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_small.jpg -O overview/images/faces_photoalbum_skateboard_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_skateboard_small_2x.jpg -O overview/images/faces_photoalbum_skateboard_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_large.jpg -O overview/images/faces_timelapse_hongkong_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_large_2x.jpg -O overview/images/faces_timelapse_hongkong_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_medium.jpg -O overview/images/faces_timelapse_hongkong_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_medium_2x.jpg -O overview/images/faces_timelapse_hongkong_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_small.jpg -O overview/images/faces_timelapse_hongkong_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_small_2x.jpg -O overview/images/faces_timelapse_hongkong_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_large.jpg -O overview/images/faces_timelapse_london_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_large_2x.jpg -O overview/images/faces_timelapse_london_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_medium.jpg -O overview/images/faces_timelapse_london_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_medium_2x.jpg -O overview/images/faces_timelapse_london_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_small.jpg -O overview/images/faces_timelapse_london_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_small_2x.jpg -O overview/images/faces_timelapse_london_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_large.jpg -O overview/images/faces_timelapse_macklake_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_large_2x.jpg -O overview/images/faces_timelapse_macklake_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_medium.jpg -O overview/images/faces_timelapse_macklake_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_medium_2x.jpg -O overview/images/faces_timelapse_macklake_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_small.jpg -O overview/images/faces_timelapse_macklake_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_small_2x.jpg -O overview/images/faces_timelapse_macklake_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_large.jpg -O overview/images/faces_timelapse_newyork_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_large_2x.jpg -O overview/images/faces_timelapse_newyork_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_medium.jpg -O overview/images/faces_timelapse_newyork_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_medium_2x.jpg -O overview/images/faces_timelapse_newyork_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_small.jpg -O overview/images/faces_timelapse_newyork_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_small_2x.jpg -O overview/images/faces_timelapse_newyork_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_large.jpg -O overview/images/faces_timelapse_shanghai_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_large_2x.jpg -O overview/images/faces_timelapse_shanghai_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_medium.jpg -O overview/images/faces_timelapse_shanghai_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_medium_2x.jpg -O overview/images/faces_timelapse_shanghai_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_small.jpg -O overview/images/faces_timelapse_shanghai_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_small_2x.jpg -O overview/images/faces_timelapse_shanghai_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_large.jpg -O overview/images/experience_2_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_large_2x.jpg -O overview/images/experience_2_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_medium.jpg -O overview/images/experience_2_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_medium_2x.jpg -O overview/images/experience_2_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_small.jpg -O overview/images/experience_2_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_2_small_2x.jpg -O overview/images/experience_2_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_large.jpg -O overview/images/experience_3_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_large_2x.jpg -O overview/images/experience_3_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_medium.jpg -O overview/images/experience_3_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_medium_2x.jpg -O overview/images/experience_3_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_small.jpg -O overview/images/experience_3_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/experience_3_small_2x.jpg -O overview/images/experience_3_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_large.jpg -O overview/images/favorites_1_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_large_2x.jpg -O overview/images/favorites_1_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_medium.jpg -O overview/images/favorites_1_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_medium_2x.jpg -O overview/images/favorites_1_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_small.jpg -O overview/images/favorites_1_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_1_small_2x.jpg -O overview/images/favorites_1_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_large.jpg -O overview/images/favorites_2_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_large_2x.jpg -O overview/images/favorites_2_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_medium.jpg -O overview/images/favorites_2_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_medium_2x.jpg -O overview/images/favorites_2_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_small.jpg -O overview/images/favorites_2_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/favorites_2_small_2x.jpg -O overview/images/favorites_2_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_large.jpg -O overview/images/email_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_large_2x.jpg -O overview/images/email_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_medium.jpg -O overview/images/email_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_medium_2x.jpg -O overview/images/email_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_small.jpg -O overview/images/email_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_small_2x.jpg -O overview/images/email_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_large.jpg -O overview/images/friends_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_large_2x.jpg -O overview/images/friends_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_medium.jpg -O overview/images/friends_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_medium_2x.jpg -O overview/images/friends_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_small.jpg -O overview/images/friends_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_small_2x.jpg -O overview/images/friends_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_large.jpg -O overview/images/connect_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_large_2x.jpg -O overview/images/connect_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_medium.jpg -O overview/images/connect_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_medium_2x.jpg -O overview/images/connect_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_small.jpg -O overview/images/connect_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_small_2x.jpg -O overview/images/connect_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_large.jpg -O overview/images/transit_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_large_2x.jpg -O overview/images/transit_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_medium.jpg -O overview/images/transit_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_medium_2x.jpg -O overview/images/transit_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_small.jpg -O overview/images/transit_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/transit_small_2x.jpg -O overview/images/transit_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_large.jpg -O overview/images/siri_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_large_2x.jpg -O overview/images/siri_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_medium.jpg -O overview/images/siri_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_medium_2x.jpg -O overview/images/siri_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_small.jpg -O overview/images/siri_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/siri_small_2x.jpg -O overview/images/siri_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_large.jpg -O overview/images/activation_lock_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_large_2x.jpg -O overview/images/activation_lock_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_medium.jpg -O overview/images/activation_lock_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_medium_2x.jpg -O overview/images/activation_lock_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_small.jpg -O overview/images/activation_lock_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/activation_lock_small_2x.jpg -O overview/images/activation_lock_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_large.jpg -O overview/images/technology_hero_background_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_large_2x.jpg -O overview/images/technology_hero_background_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_medium.jpg -O overview/images/technology_hero_background_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_medium_2x.jpg -O overview/images/technology_hero_background_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_small.jpg -O overview/images/technology_hero_background_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_background_small_2x.jpg -O overview/images/technology_hero_background_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_large.jpg -O overview/images/faces_timelapse_hongkong_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_large_2x.jpg -O overview/images/faces_timelapse_hongkong_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_medium.jpg -O overview/images/faces_timelapse_hongkong_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_medium_2x.jpg -O overview/images/faces_timelapse_hongkong_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_small.jpg -O overview/images/faces_timelapse_hongkong_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_hongkong_small_2x.jpg -O overview/images/faces_timelapse_hongkong_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_large.jpg -O overview/images/faces_timelapse_london_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_large_2x.jpg -O overview/images/faces_timelapse_london_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_medium.jpg -O overview/images/faces_timelapse_london_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_medium_2x.jpg -O overview/images/faces_timelapse_london_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_small.jpg -O overview/images/faces_timelapse_london_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_london_small_2x.jpg -O overview/images/faces_timelapse_london_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_large.jpg -O overview/images/faces_timelapse_macklake_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_large_2x.jpg -O overview/images/faces_timelapse_macklake_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_medium.jpg -O overview/images/faces_timelapse_macklake_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_medium_2x.jpg -O overview/images/faces_timelapse_macklake_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_small.jpg -O overview/images/faces_timelapse_macklake_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_macklake_small_2x.jpg -O overview/images/faces_timelapse_macklake_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_large.jpg -O overview/images/faces_timelapse_newyork_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_large_2x.jpg -O overview/images/faces_timelapse_newyork_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_medium.jpg -O overview/images/faces_timelapse_newyork_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_medium_2x.jpg -O overview/images/faces_timelapse_newyork_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_small.jpg -O overview/images/faces_timelapse_newyork_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_newyork_small_2x.jpg -O overview/images/faces_timelapse_newyork_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_large.jpg -O overview/images/faces_timelapse_shanghai_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_large_2x.jpg -O overview/images/faces_timelapse_shanghai_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_medium.jpg -O overview/images/faces_timelapse_shanghai_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_medium_2x.jpg -O overview/images/faces_timelapse_shanghai_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_small.jpg -O overview/images/faces_timelapse_shanghai_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_timelapse_shanghai_small_2x.jpg -O overview/images/faces_timelapse_shanghai_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_large.jpg -O overview/images/technology_hero_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_large_2x.jpg -O overview/images/technology_hero_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_medium.jpg -O overview/images/technology_hero_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_medium_2x.jpg -O overview/images/technology_hero_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_small.jpg -O overview/images/technology_hero_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/technology_hero_small_2x.jpg -O overview/images/technology_hero_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_large.jpg -O overview/images/email_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_large_2x.jpg -O overview/images/email_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_medium.jpg -O overview/images/email_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_medium_2x.jpg -O overview/images/email_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_small.jpg -O overview/images/email_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/email_small_2x.jpg -O overview/images/email_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_large.jpg -O overview/images/friends_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_large_2x.jpg -O overview/images/friends_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_medium.jpg -O overview/images/friends_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_medium_2x.jpg -O overview/images/friends_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_small.jpg -O overview/images/friends_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/friends_small_2x.jpg -O overview/images/friends_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_large.jpg -O overview/images/connect_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_large_2x.jpg -O overview/images/connect_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_medium.jpg -O overview/images/connect_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_medium_2x.jpg -O overview/images/connect_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_small.jpg -O overview/images/connect_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/connect_small_2x.jpg -O overview/images/connect_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_large.jpg -O overview/images/time_travel_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_large_2x.jpg -O overview/images/time_travel_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_medium.jpg -O overview/images/time_travel_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_medium_2x.jpg -O overview/images/time_travel_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_small.jpg -O overview/images/time_travel_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/time_travel_small_2x.jpg -O overview/images/time_travel_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large.jpg -O overview/images/faces_photoalbum_coolgirl_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large_2x.jpg -O overview/images/faces_photoalbum_coolgirl_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium.jpg -O overview/images/faces_photoalbum_coolgirl_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium_2x.jpg -O overview/images/faces_photoalbum_coolgirl_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small.jpg -O overview/images/faces_photoalbum_coolgirl_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small_2x.jpg -O overview/images/faces_photoalbum_coolgirl_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large.jpg -O overview/images/faces_photoalbum_coolgirl_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_large_2x.jpg -O overview/images/faces_photoalbum_coolgirl_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium.jpg -O overview/images/faces_photoalbum_coolgirl_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_medium_2x.jpg -O overview/images/faces_photoalbum_coolgirl_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small.jpg -O overview/images/faces_photoalbum_coolgirl_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/faces_photoalbum_coolgirl_small_2x.jpg -O overview/images/faces_photoalbum_coolgirl_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large.jpg -O overview/images/nightstand_lifestyle_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large_2x.jpg -O overview/images/nightstand_lifestyle_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium.jpg -O overview/images/nightstand_lifestyle_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium_2x.jpg -O overview/images/nightstand_lifestyle_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small.jpg -O overview/images/nightstand_lifestyle_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small_2x.jpg -O overview/images/nightstand_lifestyle_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large.jpg -O overview/images/nightstand_lifestyle_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large_2x.jpg -O overview/images/nightstand_lifestyle_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium.jpg -O overview/images/nightstand_lifestyle_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium_2x.jpg -O overview/images/nightstand_lifestyle_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small.jpg -O overview/images/nightstand_lifestyle_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small_2x.jpg -O overview/images/nightstand_lifestyle_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large.jpg -O overview/images/nightstand_lifestyle_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_large_2x.jpg -O overview/images/nightstand_lifestyle_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium.jpg -O overview/images/nightstand_lifestyle_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_medium_2x.jpg -O overview/images/nightstand_lifestyle_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small.jpg -O overview/images/nightstand_lifestyle_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_small_2x.jpg -O overview/images/nightstand_lifestyle_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_large.jpg -O overview/images/nightstand_lifestyle_watchoff_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_large_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_medium.jpg -O overview/images/nightstand_lifestyle_watchoff_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_medium_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_small.jpg -O overview/images/nightstand_lifestyle_watchoff_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_small_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_small_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_large.jpg -O overview/images/nightstand_lifestyle_watchoff_large.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_large_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_large_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_medium.jpg -O overview/images/nightstand_lifestyle_watchoff_medium.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_medium_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_medium_2x.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_small.jpg -O overview/images/nightstand_lifestyle_watchoff_small.jpg
wget http://images.apple.com/cn/watchos-2-preview/overview/images/nightstand_lifestyle_watchoff_small_2x.jpg -O overview/images/nightstand_lifestyle_watchoff_small_2x.jpg